name: Run Microdot Tests

on:
  push:
    branches:
      - main  # Trigger bei Push auf den "main"-Branch
  pull_request:
    branches:
      - main  # Trigger bei Pull Requests auf den "main"-Branch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run tests
        run: pytest test_server.py