name: Run Microdot Tests Playwright

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - main  # Trigger bei Push auf den "main"-Branch
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - main  # Trigger bei Pull Requests auf den "main"-Branch

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run tests
        run: pytest test_server.py